development:
  adapter: postgresql
  encoding: unicode
  database: gym_development
  pool: 5
  username: postgres
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: gym_production
  pool: 5
  username: postgres
  password:
  host: localhost
