default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  

development:
  <<: *default
  database: gymapp_development

test:
  <<: *default
  database: gymapp_test
